name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Install npm package
        run: npm ci

      - name: Build code
        run: npm run build

      - name: Empty s3 bucket
        run: aws s3 rm s3://${{ vars.S3_BUCKET_NAME }} --recursive

      - name: Push code
        run: aws s3 sync dist/ s3://${{ vars.S3_BUCKET_NAME }}

      - name: Invalidate cloudfront
        run: aws cloudfront create-invalidation --distribution-id ${{ vars.DISTRIBUTION_ID }} --paths "/*"
